In [1]:
import cv2
import numpy as np
from sklearn.cluster import KMeans

In [2]:
imlist = {}

In [3]:
path = '/home/padmach/Capabilities/ImageAnalytics/BagVisualWords/images/train/'

In [4]:
count = 0
train_labels = np.array([])
name_dict = {}
descriptor_list = []
images = None
label_count = 0
sift_object = cv2.xfeatures2d.SIFT_create()

In [5]:
from glob import glob

In [6]:
for each in glob(path+'*'):
    word = each.split("/")[-1]
    #print word #displays sub-folders - dollar_bill, accordion, motorbike, Soccer_Ball
    imlist[word]=[]
    for imagefile in glob(path+word+'/*'):
        #print imagefile # displays image_0008.jpg, image_0013.jpg
        im = cv2.imread(imagefile,0)
        imlist[word].append(im)
        count +=1
print count

58


In [7]:
for word, image in imlist.iteritems():
    name_dict[str(label_count)] =word
    for im in image:
        train_labels = np.append(train_labels, label_count)
        kp, des = sift_object.detectAndCompute(im, None)
        print(des.shape)
        descriptor_list.append(des)
    label_count +=1

(467, 128)
(474, 128)
(644, 128)
(632, 128)
(638, 128)
(416, 128)
(389, 128)
(533, 128)
(500, 128)
(511, 128)
(620, 128)
(486, 128)
(503, 128)
(485, 128)
(257, 128)
(161, 128)
(935, 128)
(250, 128)
(493, 128)
(327, 128)
(442, 128)
(409, 128)
(236, 128)
(181, 128)
(112, 128)
(727, 128)
(93, 128)
(81, 128)
(225, 128)
(121, 128)
(203, 128)
(208, 128)
(185, 128)
(132, 128)
(215, 128)
(175, 128)
(170, 128)
(174, 128)
(257, 128)
(192, 128)
(211, 128)
(162, 128)
(161, 128)
(213, 128)
(489, 128)
(366, 128)
(729, 128)
(843, 128)
(931, 128)
(810, 128)
(990, 128)
(795, 128)
(380, 128)
(881, 128)
(787, 128)
(567, 128)
(1101, 128)
(827, 128)


In [8]:
name_dict

{'0': 'dollar_bill',
 '1': 'motorbike1',
 '2': 'Soccer_Ball',
 '3': 'motorbike',
 '4': 'accordion'}

In [9]:
#lentrain_labels) # 56
#type(train_labels) #numpy.ndarray
train_labels

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  4.])

In [10]:
#type(des) #numpy.ndarray
#len(des) #827
des.shape

(827, 128)

In [11]:
type(descriptor_list) #list 
len(descriptor_list) #58
len(descriptor_list[55]) #567
type(descriptor_list[55]) #numpy.ndarray
descriptor_list[55].shape

(567, 128)

In [12]:
type(descriptor_list[0])

numpy.ndarray

In [13]:
vStack = descriptor_list[0]

In [14]:
type(vStack)

numpy.ndarray

In [15]:
for remaining in descriptor_list:
    vStack = np.vstack((vStack, remaining))

In [16]:
vStack[0]

array([   0.,    0.,    1.,   14.,   30.,   11.,    1.,    0.,   67.,
          7.,    2.,    8.,   16.,   12.,    1.,    4.,  193.,   22.,
          0.,    0.,    0.,    0.,    0.,    6.,   55.,    4.,    0.,
          1.,  116.,    4.,    0.,    1.,    0.,    0.,    5.,   25.,
         30.,    4.,    1.,    0.,   89.,    5.,    4.,   13.,   10.,
          9.,    2.,    6.,  193.,    9.,    0.,    0.,    0.,    0.,
          0.,   15.,   69.,    6.,    0.,    6.,  139.,    1.,    0.,
          3.,    2.,    1.,    2.,    6.,   30.,    7.,    2.,    1.,
         90.,    6.,    3.,   11.,    9.,   11.,    4.,    3.,  193.,
          8.,    0.,    1.,    1.,    1.,    0.,   19.,   61.,    1.,
          0.,    3.,  139.,    5.,    0.,    8.,    0.,    1.,    6.,
         13.,   14.,    5.,    0.,    0.,   81.,    3.,    2.,   17.,
         12.,    2.,    0.,    3.,  193.,    6.,    0.,    0.,    1.,
          0.,    0.,    8.,   48.,    2.,    0.,    3.,  113.,    5.,
          0.,    2.]

In [17]:
vStack[1]

array([  31.,   46.,    1.,    0.,    0.,    0.,    0.,    0.,   63.,
         49.,    1.,    1.,    1.,    0.,    0.,   10.,  176.,    5.,
          0.,    0.,    1.,    0.,    0.,   62.,   97.,    5.,    0.,
          6.,   46.,    1.,    0.,   12.,   26.,   33.,    4.,    2.,
          2.,    1.,    0.,    0.,  121.,   80.,    5.,    0.,    0.,
          0.,    0.,    1.,  176.,   23.,    0.,    0.,    0.,    0.,
          0.,   16.,   93.,   11.,    1.,   16.,   60.,    0.,    0.,
          3.,   12.,   18.,    5.,    3.,   10.,   19.,    4.,    2.,
        168.,   48.,    3.,    0.,    0.,    0.,    1.,    3.,  176.,
          9.,    0.,    0.,    0.,    0.,    0.,   28.,   63.,    4.,
          2.,   15.,   74.,    6.,    2.,   12.,    2.,    2.,    3.,
         17.,   11.,   16.,    4.,    1.,  149.,   32.,    4.,    4.,
          1.,    1.,    1.,    3.,  176.,    5.,    0.,    0.,    0.,
          0.,    0.,   39.,   36.,    0.,    0.,    7.,   84.,    5.,
          1.,   17.]

In [18]:
kmeans_obj = KMeans(n_clusters = 100)

In [19]:
kmeans_ret = kmeans_obj.fit_predict(vStack)

In [20]:
type(kmeans_ret)

numpy.ndarray

In [21]:
kmeans_ret

array([22, 77, 13, ...,  0, 46, 53], dtype=int32)

In [22]:
type(kmeans_ret)

numpy.ndarray

In [23]:
kmeans_ret.shape

(25969,)

In [24]:
#develop vocabulary
mega_histogram = np.array([np.zeros(100) for i in range(58)])


In [25]:
mega_histogram.shape

(58, 100)

In [26]:
old_count =0 
for i in range(58):
    l = len(descriptor_list[i])
    for j in range(l):
        idx = kmeans_ret[old_count+j]
        mega_histogram[i][idx] +=1
    old_count+=l

In [97]:
type(mega_histogram[0][0])

numpy.float64

In [171]:
surf_object = cv2.xfeatures2d.SURF_create()

In [184]:
vStack[0]

array([   0.,    0.,    1.,   14.,   30.,   11.,    1.,    0.,   67.,
          7.,    2.,    8.,   16.,   12.,    1.,    4.,  193.,   22.,
          0.,    0.,    0.,    0.,    0.,    6.,   55.,    4.,    0.,
          1.,  116.,    4.,    0.,    1.,    0.,    0.,    5.,   25.,
         30.,    4.,    1.,    0.,   89.,    5.,    4.,   13.,   10.,
          9.,    2.,    6.,  193.,    9.,    0.,    0.,    0.,    0.,
          0.,   15.,   69.,    6.,    0.,    6.,  139.,    1.,    0.,
          3.,    2.,    1.,    2.,    6.,   30.,    7.,    2.,    1.,
         90.,    6.,    3.,   11.,    9.,   11.,    4.,    3.,  193.,
          8.,    0.,    1.,    1.,    1.,    0.,   19.,   61.,    1.,
          0.,    3.,  139.,    5.,    0.,    8.,    0.,    1.,    6.,
         13.,   14.,    5.,    0.,    0.,   81.,    3.,    2.,   17.,
         12.,    2.,    0.,    3.,  193.,    6.,    0.,    0.,    1.,
          0.,    0.,    8.,   48.,    2.,    0.,    3.,  113.,    5.,
          0.,    2.]

In [191]:
for d in descriptor_list:
    print(len(d))

467
474
644
632
638
416
389
533
500
511
620
486
503
485
935
250
493
327
442
409
236
181
112
727
93
81
225
121
203
208
185
132
215
175
170
174
257
192
211
162
161
213
489
366
729
843
931
810
990
795
380
881
787
567
1101
827


In [28]:
descriptor_list

[array([[  0.,   0.,   1., ...,   5.,   0.,   2.],
        [ 31.,  46.,   1., ...,   5.,   1.,  17.],
        [  4.,   7.,   5., ...,   0.,   0.,   0.],
        ..., 
        [  1.,   0.,   0., ...,   1.,   1.,   0.],
        [  8.,   0.,   0., ...,  32.,  12.,   4.],
        [ 15.,   0.,   0., ...,   0.,   0.,   0.]], dtype=float32),
 array([[   0.,    2.,   19., ...,    0.,    0.,   10.],
        [   0.,    5.,   41., ...,    1.,   32.,  123.],
        [   1.,    2.,    8., ...,    1.,   11.,   57.],
        ..., 
        [  11.,    5.,    5., ...,    7.,   29.,   15.],
        [   1.,   60.,  123., ...,    0.,    0.,    0.],
        [ 135.,    7.,    0., ...,    0.,    4.,   36.]], dtype=float32),
 array([[ 166.,   44.,    7., ...,    0.,    0.,    1.],
        [ 164.,    4.,    1., ...,    2.,    4.,   11.],
        [  69.,   14.,   30., ...,    0.,    1.,    4.],
        ..., 
        [   0.,    0.,    0., ...,    2.,   32.,   59.],
        [   0.,    0.,    0., ...,   32.,   34.,

In [31]:
len(vStack)

25969

In [75]:
kmeans_fit = kmeans_obj.fit(vStack)

In [77]:
kmeans_predict = kmeans_fit.predict(vStack)

In [80]:
kmeans_predict.shape

(25969,)

In [85]:
kmeans_fit.cluster_centers_[0].shape

(128,)

In [86]:
type(kmeans_predict)

numpy.ndarray

In [87]:
kmeans_predict[0]

21

In [89]:
type(kmeans_predict[0])

numpy.int32

In [90]:
len(kmeans_predict[0])

TypeError: object of type 'numpy.int32' has no len()

In [91]:
kmeans_predict.shape

(25969,)

In [92]:
kmeans_ret.shape

(25969,)

In [31]:
mega_histogram[1]

array([ 24.,   3.,   1.,   3.,   4.,   5.,   8.,   4.,   3.,   2.,   8.,
         2.,   9.,   8.,   2.,   3.,   5.,   2.,   2.,   0.,   0.,   6.,
        10.,   1.,   4.,   1.,   0.,   4.,   4.,   5.,   5.,  12.,   4.,
         2.,   7.,   6.,   8.,   8.,   3.,   7.,   2.,  26.,   2.,   4.,
         0.,   4.,   5.,   4.,   3.,   6.,  13.,   2.,   2.,   1.,   5.,
         5.,   0.,   0.,   5.,  14.,   9.,   3.,   3.,   6.,   5.,   5.,
         3.,   3.,   2.,   3.,  10.,   3.,   0.,   5.,   7.,  13.,   5.,
         3.,   1.,   7.,   6.,   4.,   4.,   3.,   6.,   7.,  10.,   5.,
         5.,   8.,   1.,   1.,   4.,   0.,   1.,   3.,   3.,   3.,   5.,
         1.])

In [32]:
mega_histogram[0]

array([ 24.,   3.,   1.,   3.,   4.,   5.,   7.,   4.,   3.,   2.,   8.,
         2.,   9.,   8.,   2.,   3.,   5.,   2.,   2.,   0.,   0.,   6.,
        10.,   1.,   4.,   1.,   0.,   4.,   4.,   5.,   5.,  12.,   4.,
         2.,   7.,   6.,   8.,   8.,   3.,   6.,   2.,  26.,   2.,   4.,
         0.,   4.,   5.,   3.,   3.,   6.,  13.,   2.,   2.,   1.,   5.,
         5.,   0.,   0.,   4.,  14.,   9.,   3.,   3.,   6.,   5.,   5.,
         3.,   3.,   2.,   3.,  10.,   3.,   0.,   5.,   7.,  12.,   5.,
         3.,   1.,   7.,   6.,   4.,   4.,   3.,   6.,   7.,  10.,   5.,
         5.,   8.,   1.,   1.,   3.,   0.,   0.,   3.,   3.,   3.,   5.,
         1.])

In [33]:
mega_histogram[2]

array([ 16.,   5.,   4.,   0.,   8.,   1.,   9.,   5.,   3.,   6.,  16.,
         7.,   5.,  15.,   1.,   2.,  14.,   3.,   1.,   2.,   4.,  12.,
         3.,   6.,  11.,   6.,   0.,  14.,   1.,   4.,   2.,  13.,  15.,
         5.,   4.,   5.,   3.,   5.,  13.,   5.,   4.,  14.,   5.,   5.,
         3.,   6.,   2.,   7.,   1.,   7.,  10.,  15.,   5.,   3.,   7.,
        10.,   0.,   5.,   5.,  23.,   8.,   4.,   2.,  14.,   9.,   4.,
         3.,   5.,   7.,   6.,   5.,   7.,   0.,   6.,   9.,  12.,   7.,
         0.,   9.,   6.,  10.,  11.,   6.,   5.,   9.,   3.,  10.,   4.,
         2.,   6.,   4.,   8.,   7.,   3.,   9.,   9.,   3.,   7.,  11.,
         3.])

In [34]:
mega_histogram[3]

array([ 18.,  13.,   6.,   2.,   6.,   5.,  19.,   4.,   2.,   4.,   8.,
         5.,   2.,  18.,   9.,   1.,   7.,   3.,   8.,   5.,   3.,   3.,
         7.,   4.,  16.,   4.,   1.,  34.,   0.,  10.,   4.,  11.,   7.,
         2.,   1.,   4.,   2.,   6.,   4.,   4.,   4.,   7.,   7.,   2.,
         2.,  12.,   7.,   5.,   7.,   3.,   5.,  14.,   9.,   3.,   4.,
        11.,   0.,   3.,   9.,   4.,  11.,   1.,   3.,  12.,   5.,   4.,
         6.,  13.,   6.,  10.,   9.,   6.,   0.,   7.,  12.,  15.,  12.,
         1.,   4.,   2.,   5.,   4.,   0.,   8.,   9.,   4.,  14.,  16.,
         5.,   5.,   3.,   5.,   2.,   5.,   2.,   3.,   7.,   0.,   2.,
         4.])

In [42]:
len(descriptor_list[37])

174

In [43]:
mega_histogram[37]

array([ 0.,  1.,  1.,  0.,  3.,  1.,  1.,  3.,  1.,  0.,  2.,  2.,  4.,
        2.,  0.,  0.,  1.,  0.,  5.,  1.,  4.,  1.,  1.,  1.,  2.,  1.,
        0.,  1.,  0.,  0.,  3.,  1.,  1.,  0.,  0.,  2.,  2.,  1.,  0.,
        0.,  4.,  1.,  3.,  0.,  1.,  4.,  0.,  4.,  2.,  2.,  0.,  5.,
        0.,  5.,  0.,  5.,  0.,  6.,  5.,  1.,  0.,  0.,  0.,  1.,  3.,
        2.,  2.,  0.,  4.,  2.,  0.,  0.,  0.,  4.,  0.,  4.,  3.,  1.,
        1.,  2.,  5.,  5.,  1.,  2.,  5.,  0.,  2.,  3.,  2.,  2.,  6.,
        0.,  0.,  2.,  1.,  1.,  4.,  0.,  3.,  4.])